### ISSUE TITLE
lchika_pattern6_2.py 配列へスイッチ入力データの記録

### ISSUE THREAD

**Issue by ShinoBishin** [kohey0701/L_chika#2]
配列にスイッチ入力データを記録してその値を順番に取り出し、LEDを点灯する。

・スイッチ入力データを配列に書き込むまでは成功
・配列に入ったデータを順に取り出し、LEDを点灯するプロセスが未完成
・別のスイッチ(27番)からの入力で記録、点灯モードの切り替えを行いたい

**Comment by akif999** [comment]
以下を見た感じ、↑に書いている通り、LED を点灯する部分だけ作ったら完成しそう。 配列に入れる部分は自分が想定した通りの作りになっています。
https://github.com/kohey0701/L_chika/blob/master/lchika_pattern6/lchika_pattern6_2.py

もしかしたら 500ms ごとのサンプリングだと精度が低すぎるかもしれないけど、それは動かしながら調整すればよさげ。

**Comment by ShinoBishin** [comment]
・スイッチ入力の読み取り制度向上の為配列への書き込みサンプルレートを1000ms毎に変更
・python3における配列から順にデータを取り出す(サンプルレートをそろえて)方法を調査中

**Comment by ShinoBishin** [comment]
## 先刻のコミットを持って
・「スイッチの入力を100ms毎に記録する」
・「記録したデータを100ms毎に取り出してLEDに出力する」
上記2点の実装とハードの動作に成功
